### ISSUE TITLE
HTTP2Socks 和另一个都不可用该怎么办

### ISSUE THREAD

**Issue by eeeeeeeeee-code** [vicnoah/ptunnel#4]
HTTP2Socks 和 TCP2Socks都不可用，本地起了，但是连接本地端口后，访问网站是吧，代理一直是处于连接后关闭，感觉是没有成功转发过去

**Comment by eeeeeeeeee-code** [comment]
![image](https://github.com/user-attachments/assets/17c01198-b065-40f7-9002-39ad6b255a7f)
这个本地测试的socks代理，直接连接可以，但是使用这个转发不行

**Comment by vicnoah** [comment]
> ![image](https://private-user-images.githubusercontent.com/115862499/356785068-17c01198-b065-40f7-9002-39ad6b255a7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MjcxMTgsIm5iZiI6MTcyMzQyNjgxOCwicGF0aCI6Ii8xMTU4NjI0OTkvMzU2Nzg1MDY4LTE3YzAxMTk4LWIwNjUtNDBmNy05MDAyLTM5YWQ2YjI1NWE3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwMTQwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWRlZTE0NmU2MjkwN2Y5ZWQxZGI5NTgwZmRlMjQzZWYxMjU4NmE5NjRlYzY3ZmVjNjA0OWExNDYwYzU4YjU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AtxjEwH62Hrf4oDxFW6yqtXULDQjYfBX_SCTmRSeOFE) 这个本地测试的socks代理，直接连接可以，但是使用这个转发不行

这个项目已经不维护，功能也并没有实现。有更好用的工具，所以这项目已经搁置了，你可以使用clash等工具。
